# Generated by Django 2.2 on 2024-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_units_supplied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
